#build
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    #deploy
    args:
      - app
      - deploy
      - client-admin/app.yaml
      - '--quiet'
options:
  logging: CLOUD_LOGGING_ONLY
