steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'deploy/backend/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/carpooling-backend', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/carpooling-backend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - carpooling-backend
      - '--image=gcr.io/$PROJECT_ID/carpooling-backend'
      - '--region=asia-southeast2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production'
images:
  - 'gcr.io/$PROJECT_ID/carpooling-backend'
options:
  logging: CLOUD_LOGGING_ONLY
