runtime: nodejs22
service: carpooling-user

handlers:
  - url: /(.*\.(css|js|png|jpg|jpeg|gif|svg|ico|webp))
    static_files: \1
    upload: .*\.(css|js|png|jpg|jpeg|gif|svg|ico|webp)$
    secure: always

  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always
